version: '3'
services:
  ara:
    image: 'ara:latest'
    ports:
      - '8000:8000'
    environment:
      - ARA_DATABASE=postgresql+psycopg2://ara:ara@db:5432/ara
  db:
    image: 'postgres:11'
    ports: 
      - '5432:5432'

    shm_size: '256mb'
    environment:
      - POSTGRES_USER=ara
      - POSTGRES_PASSWORD=ara
      - POSTGRES_DB=ara
